// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Student_Assistant.DbContexts;

namespace Student_Assistant.Migrations
{
    [DbContext(typeof(StudentAssistantDbContext))]
    partial class StudentAssistantDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("Student_Assistant.DTOs.AnswerDTO", b =>
                {
                    b.Property<Guid>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Answered")
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QuestionContext")
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("Student_Assistant.DTOs.QuestionDTO", b =>
                {
                    b.Property<Guid>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Answer1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Answer2")
                        .HasColumnType("TEXT");

                    b.Property<string>("Answer3")
                        .HasColumnType("TEXT");

                    b.Property<string>("Answer4")
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QuestionContext")
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
